### ISSUE TITLE
Docs Missing Jobs

### ISSUE THREAD

**Issue by psaunders** [turbulent/substance#25]
Docs should cover jobs, specifically that you can define the user to use and what things are available

```
jobs:
  install:
    image: turbulent/heap-app-dev:5.2.0
    command: ['/bin/sh', '-c', 'cd /vol/website && npm install && composer install']
    user: heap
    volume:
      - "{{SUBENV_BASEPATH}}:/vol/website"
```
