### ISSUE TITLE
Useless Error

### ISSUE THREAD

**Issue by psaunders** [turbulent/substance#33]
![image](https://user-images.githubusercontent.com/424956/37534517-728e3910-291b-11e8-9e7f-4dcc437036fc.png)

```
  mediabroker:
    image: alekzonder/puppeteer:1.1.1
    hostname: mediabroker
    shm-size: 1G
    volume:
      - "{{SUBENV_BASEPATH}}/mediabroker:/mediabroker"
```
